proxy-providers:

  Love:
    url: "https://share.112233.cyou/text.txt"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
    override:
      udp: true

  Enet:
    url: "https://www.easysub.net/s/ug6ihl16w4jn"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿
    override:
      udp: true


proxies:
  - {name: ç›´è¿, type: direct, udp: true}
  - {name: æ‹’ç», type: reject}

# ========================
# ä¸»è¦ç«¯å£è®¾ç½®
# ========================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
unified-delay: true
tcp-concurrent: true
allow-lan: true
mode: rule
log-level: info
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true

external-controller: 0.0.0.0:9090

# ========================
# DNS è®¾ç½®
# ========================
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.lan"
    - "+.local"
    - "geosite:cn"
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"

ipv6: true


# ========================
# ç­–ç•¥ç»„å®šä¹‰
# ========================
default: &default
  type: select
  proxies: [ğŸ¯ æ€»æ¨¡å¼, ğŸ‡­ğŸ‡° é¦™æ¸¯-æ•…è½¬, ğŸ‡¨ğŸ‡³ å°æ¹¾-æ•…è½¬, ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ•…è½¬, ğŸ‡¸ğŸ‡¬ ç‹®åŸ-æ•…è½¬, ğŸ‡ºğŸ‡² ç¾å›½-æ•…è½¬, ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨, ğŸ‡ºğŸ‡³ å…¶ä»–-è‡ªåŠ¨, ç›´è¿]

proxy-groups:
  - {name: ğŸ¯ æ€»æ¨¡å¼, type: select, proxies: [ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, ğŸ‡­ğŸ‡° é¦™æ¸¯-æ•…è½¬, ğŸ‡¨ğŸ‡³ å°æ¹¾-æ•…è½¬, ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ•…è½¬, ğŸ‡¸ğŸ‡¬ ç‹®åŸ-æ•…è½¬, ğŸ‡ºğŸ‡² ç¾å›½-æ•…è½¬, ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨, ğŸ‡ºğŸ‡³ å…¶ä»–-è‡ªåŠ¨, ç›´è¿]}
  - {name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢, type: select, include-all: true, filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"}
  - {name: ğŸ“² Telegram, <<: *default}
  - {name: ğŸ¶ Tiktok, <<: *default}
  - {name: ğŸ‘¨ğŸ¿â€ğŸ’» GitHub, <<: *default}
  - {name: ğŸ–¥ï¸ OpenAI, <<: *default}
  - {name: ğŸŒ å›½å¤–ç½‘ç«™, <<: *default}
  - {name: ğŸ“¹ Youtube, <<: *default}
  - {name: ğŸ–¥ï¸ Google, <<: *default}
  - {name: ğŸ¥ Netflix, <<: *default}
  - {name: ğŸ¶ Spotify, <<: *default}
  - {name: ğŸ¥ Disney+, <<: *default}
  - {name: ğŸ¥ Max, <<: *default}
  - {name: â“‚ï¸ å¾®è½¯äº‘ç›˜, <<: *default}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, <<: *default}
  - {name: ğŸ è‹¹æœæœåŠ¡, <<: *default}
  - {name: ğŸ” NFSW, <<: *default}
  - {name: ğŸ® æ¸¸æˆå¹³å°, <<: *default}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [ç›´è¿, ğŸš€ æ‰‹åŠ¨åˆ‡æ¢] }
  - {name: ğŸ›‘ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [æ‹’ç», ç›´è¿]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *default}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯-æ•…è½¬, type: fallback, interval: 180, lazy: false, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨, ğŸ‡­ğŸ‡° é¦™æ¸¯-è‡ªåŠ¨]}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"}
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾-æ•…è½¬, type: fallback, interval: 180, lazy: false, proxies: [ğŸ‡¨ğŸ‡³ å°æ¹¾-æ‰‹åŠ¨, ğŸ‡¨ğŸ‡³ å°æ¹¾-è‡ªåŠ¨]}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ•…è½¬, type: fallback, interval: 180, lazy: false, proxies: [ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨, ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è‡ªåŠ¨]}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-æ•…è½¬, type: fallback, interval: 180, lazy: false, proxies: [ğŸ‡¸ğŸ‡¬ ç‹®åŸ-æ‰‹åŠ¨, ğŸ‡¸ğŸ‡¬ ç‹®åŸ-è‡ªåŠ¨]}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½-æ•…è½¬, type: fallback, interval: 180, lazy: false, proxies: [ğŸ‡ºğŸ‡² ç¾å›½-æ‰‹åŠ¨, ğŸ‡ºğŸ‡² ç¾å›½-è‡ªåŠ¨]}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"}
  - {name: ğŸ‡ºğŸ‡³ å…¶ä»–-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).)*$"}

# ========================
# è§„åˆ™å¼•æ“ï¼ˆrulesï¼‰
# ========================
rules:
  - RULE-SET,direct_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,china_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,china_ip,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,private_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,my_domain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ads_domain,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,privacy_domain,ğŸ›‘ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,telegram_domain,ğŸ“² Telegram
  - RULE-SET,telegram_ip,ğŸ“² Telegram,no-resolve
  - RULE-SET,tiktok_domain,ğŸ¶ Tiktok
  - RULE-SET,github_domain,ğŸ‘¨ğŸ¿â€ğŸ’» GitHub
  - RULE-SET,chatgpt_domain,ğŸ–¥ï¸ OpenAI
  - RULE-SET,claude_domain,ğŸ–¥ï¸ OpenAI
  - RULE-SET,perplexity_domain,ğŸ–¥ï¸ OpenAI
  - RULE-SET,copilot_domain,ğŸ–¥ï¸ OpenAI
  - RULE-SET,youtube_domain,ğŸ“¹ Youtube
  - RULE-SET,netflix_domain,ğŸ¥ Netflix
  - RULE-SET,netflix_ip,ğŸ¥ Netflix,no-resolve
  - RULE-SET,spotify_domain,ğŸ¶ Spotify
  - RULE-SET,disney_domain,ğŸ¥ Disney+
  - RULE-SET,max_domain,ğŸ¥ Max
  - RULE-SET,apple_domain,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,apple_cn_domain,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,onedrive_domain,â“‚ï¸ å¾®è½¯äº‘ç›˜
  - RULE-SET,microsoft_domain,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,nfsw_domain,ğŸ” NFSW
  - RULE-SET,steam_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,epic_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,ea_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,blizzard_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,ubi_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,playstation_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,nintend_domain,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,google_domain,ğŸ–¥ï¸ Google
  - RULE-SET,google_ip,ğŸ–¥ï¸ Google,no-resolve
  - RULE-SET,proxy_domain,ğŸŒ å›½å¤–ç½‘ç«™
  - RULE-SET,globe_domain,ğŸŒ å›½å¤–ç½‘ç«™
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# ========================
# è§„åˆ™é›†æä¾›è€…
# ========================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  chatgpt_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"}
  claude_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list"}
  perplexity_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/perplexity.mrs"}
  copilot_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Copilot.list"}
  github_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"}
  telegram_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"}
  telegram_ip: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"}
  apple_cn_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs"}
  apple_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"}
  onedrive_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list"}
  microsoft_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"}
  tiktok_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"}
  netflix_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"}
  netflix_ip: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"}
  disney_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"}
  max_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs"}
  spotify_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs"}
  nfsw_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/carlosxu312/proxy_config/master/clash/rule/nfsw.list"}
  steam_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"}
  epic_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list"}
  ea_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list"}
  blizzard_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list"}
  ubi_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list"}
  playstation_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PlayStation/PlayStation.list"}
  nintend_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list"}
  proxy_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list"}
  globe_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"}
  direct_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list"}
  china_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"}
  china_ip: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"}
  my_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/carlosxu312/proxy_config/master/clash/rule/direct.list"}
  private_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"}
  ads_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Classical.yaml"}
  privacy_domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml"}
  youtube_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"}
  google_domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"}
  google_ip: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"}
